```bash
[master]
172.16.16.x
[crashoverride]
172.16.16.x
[acidburn]
172.16.16.x
[cerealkiller]
172.16.16.x

[master:vars]
ansible_ssh_user=eugene
ansible_ssh_pass=
[crashoverride:vars]
ansible_ssh_user=zerocool
ansible_ssh_pass=
[acidburn:vars]
ansible_ssh_user=kate
ansible_ssh_pass=
[cerealkiller:vars]
ansible_ssh_user=emmanuel
ansible_ssh_pass=
```